### ISSUE TITLE
new article type gets externalally posted

### ISSUE THREAD

**Issue by diplix** [mauricerenck/indieConnector#21]
so far i only used one page type yet („notes“ as in the kirby starterkit) and also have this in my config.php:
```
	'mauricerenck.indieConnector.send.allowedTemplates' => ['note'],
```
i even changed the default setting in site/plugins/indieconnector/blueprints/fields/block-webmentions.yml
```
    enableExternalPosting:
        label: External Posting
        type: toggle
        default: false
        width: 1/3
```
however, when i created a new page type („recipe“) yesterday and published two recipes, they got posted:

https://bsky.app/profile/wirres.net/post/3loca24n7q42r
https://bsky.app/profile/wirres.net/post/3lochnnokl52s
https://mstdn.io/@ix/114446431587888119
https://mstdn.io/@ix/114445896054128203

haven’t looked at any logs, if there are any, but this is kind of inexplicable?
when i include the indieconnector blueprint extemsion in my newly created recipe blueprint, it looks like this (havent had that in the blueprint before):

![Image](https://github.com/user-attachments/assets/817ad570-e0b3-4ce1-9742-ee52ff882a1b)

i’ll try publisheng a recipe with this in place later, and hope that this will actually prevent posting externaly …
